apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker_nodejs_demo
  labels:
    app: docker_nodejs_demo
spec:
  selector:
    matchLabels:
        app: docker_nodejs_demo
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docker_nodejs_demo
    spec:
      containers:
        - name: docker_nodejs_demo
          image: <relace-with-registry-id>.dkr.ecr.us-east-2.amazonaws.com/docker_nodejs_demo:latest
          ports:
            - containerPort: 4000
              protocol: TCP
          imagePullPolicy: Always